// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NodiusRelay$Type } from "./NodiusRelay";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NodiusRelay"]: NodiusRelay$Type;
    ["contracts/NodiusRelay.sol:NodiusRelay"]: NodiusRelay$Type;
  }

  interface ContractTypesMap {
    ["NodiusRelay"]: GetContractReturnType<NodiusRelay$Type["abi"]>;
    ["contracts/NodiusRelay.sol:NodiusRelay"]: GetContractReturnType<NodiusRelay$Type["abi"]>;
  }
}
