'use client';

import { Roboto } from "next/font/google"; 
import { ThemeProvider } from "@/components/theme-provider";
import "@/styles/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className} suppressHydrationWarning>
      <head>
          <title>Nodius</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" type="image/x-icon" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-tersiery">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          forcedTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <div className="relative bg-background min-h-screen shadow-2xl mx-auto lg:max-w-xl">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}