'use client';

import { PrivyProvider } from '@privy-io/react-auth';
import { Roboto } from "next/font/google"; 
import { ThemeProvider } from "@/components/theme-provider";
import { PrivyUserSynchronizer } from '@/hooks/PrivyUserSynchronizer'; 
import "@/styles/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className} suppressHydrationWarning>
      <head>
          <title>Nodius</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" type="image/x-icon" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <PrivyProvider 
            appId={process.env.NEXT_PUBLIC_PRIVY_APP_ID || ''}
            config={{
              appearance: {
                accentColor: "#ff00c8",
                theme: "dark",
                showWalletLoginFirst: true,
                logo: "logo.png",
              },
              loginMethods: [
                "wallet",
                "email",
                "telegram"
              ],
              embeddedWallets: {
                ethereum: {
                  createOnLogin: 'users-without-wallets'
                },
                solana: {
                  createOnLogin: 'users-without-wallets'
                },
                requireUserPasswordOnCreate: false,
              },
          }}
        >
          <PrivyUserSynchronizer /> 
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            forcedTheme="dark"
            enableSystem={false}
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}